FROM golang:alpine AS build
RUN apk --no-cache add gcc g++
WORKDIR /go/src/app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN GOOS=linux CGO_ENABLED=1 go build -o ./bin/web-app ./cmd/web/
FROM alpine:latest
WORKDIR /usr/bin
RUN apk --no-cache add ca-certificates
COPY --from=build /go/src/app/bin/web-app .
COPY ./ui ./ui
COPY ./data ./data
ENTRYPOINT [ "./web-app" ]
CMD ["--help"]